//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaDGT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConductorVehiculo
    {
        public int id { get; set; }
        public string matricula { get; set; }
        public string dni { get; set; }
    
        public virtual Conductores Conductores { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
