//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaDGT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infracciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infracciones()
        {
            this.InfraccionVehiculo = new HashSet<InfraccionVehiculo>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int puntos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfraccionVehiculo> InfraccionVehiculo { get; set; }
    }
}
